[package]
name = "application"
version = "0.1.0"
edition = "2024"

[dependencies]
domain = {path = "../domain"}
autoagents = {version = "0.3.4", features = ["deepseek", "openrouter"]}
autoagents-derive = "0.3.4"
axum = {version = "0.8.8", features = ["tokio"]}
tokio = {version = "1.49.0", features = ["rt-multi-thread", "macros"]}
uuid = "1.21.0"
derive_more = {version = "2.1.1", features = ["from", "into"]}
thiserror = "2.0.18"
