[package]
name = "infrastructure"
version = "0.1.0"
edition = "2024"

[dependencies]
domain = { path = "../domain" }
application = { path = "../application" }
async-trait = "0.1.89"
chrono = { version = "0.4.42", features = ["serde"] }
diesel = { version = "2.3.6", features = ["postgres", "r2d2", "chrono", "uuid", "serde_json"] }
diesel_migrations = "2.3.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
reqwest = { version = "0.12.24", default-features = false, features = ["json", "rustls-tls"] }
qdrant-client = "1.17.0"
uuid = { version = "1.21.0", features = ["serde", "v4"] }
thiserror = "2.0.18"
diesel-derive-enum = {version = "2.1.0", features = ["postgres"]}
autoagents = {version = "0.3.6", features = ["openrouter", "openai"]}
autoagents-derive = "0.3.6"
